export type ReleaseType = "single" | "album" | "ep";

export type EmbedProvider =
  | "bandcamp"
  | "apple"
  | "spotify"
  | "deezer"
  | "soundcloud"
  | "youtube";

export interface Embed {
  provider: EmbedProvider;
  /** Full iframe src URL */
  src: string;
  /** Optional custom height in px */
  height?: number;
}

export interface Links {
  bandcamp?: string;
  spotify?: string;
  soundcloud?: string;
  apple?: string;
  tidal?: string;
  youtube?: string;
  deezer?: string;
}

export type Status = "pending" | "approved" | "rejected";

export interface Recommendation {
  id: string;
  type: ReleaseType;
  artist: string;
  title: string;
  label: string;
  /** ISO date string */
  releaseDate: string;
  description: string;
  /** True when `description` was generated by scripts/preview-descriptions.mjs
   *  as a placeholder. The LLM writer will overwrite these safely; the admin
   *  UI can also surface the fact that the copy is provisional. */
  descriptionPreview?: boolean;
  tags: string[];
  links: Links;
  embed?: Embed | null;
  /** For singles: a real music video (not just audio upload) */
  musicVideoUrl?: string | null;
  status: Status;
  /** When approved/published, used for ordering in public feed */
  approvedAt?: string | null;
  /** Optional real cover image (from iTunes/etc). Falls back to motif when null. */
  coverImageUrl?: string | null;
  /** Press sources that have also written about this artist/release around
   *  the time we discovered it. Populated by the daily sync (e.g. The
   *  Quietus RSS). Admin UI uses this to highlight higher-signal records
   *  in the pending queue. Empty array / undefined means "no press signal",
   *  not "no press coverage exists". */
  pressMentions?: string[];
  /** Cover art treatment hint (used as fallback when coverImageUrl is null) */
  cover: {
    /** Background color */
    bg: string;
    /** Foreground color */
    fg: string;
    /** Visual motif: solid | dots | bars | disc | grid */
    motif: "solid" | "dots" | "bars" | "disc" | "grid";
  };
}

export interface FeedPage {
  items: Recommendation[];
  /** ISO date string of oldest releaseDate in this page; pass back as cursor for next page */
  nextCursor: string | null;
  hasMore: boolean;
}
