/**
 * Disquet monitoring pool - the single source of truth.
 *
 * This file is the ONLY place to change what the site tracks. Every sync
 * script (sync-artists, sync-labels, sync-festivals, sync-nts) reads from
 * these arrays. Treat it as a guide for ongoing monitoring, not a one-off
 * seed list: anything here gets checked every time a sync runs.
 *
 * House rules:
 *  - Prefer the artist's/label's canonical presentation (case, punctuation).
 *    Discogs and iTunes do case-insensitive matches, but the display name is
 *    what ends up on the site when a record is created.
 *  - If an artist records under multiple aliases, list each separately.
 *  - Don't add things you don't genuinely want on the site; the admin queue
 *    is the last line of defence, not the first.
 *  - Comment-out rather than delete when removing, so the history is visible.
 */

export const ARTISTS = [
  // Core pool (early seeds)
  "H.LLS",
  "Djrum",
  "Skee Mask",
  "Oneohtrix Point Never",
  "Daniel Lopatin",
  "Lauren Duffus",
  "John Glacier",
  "Helen Island",
  "Dean Blunt",
  "ear",
  "Andy Stott",
  "Nicolas Jaar",
  "Earl Sweatshirt",
  "Andrea",
  "Stenny",
  "Purelink",
  "Ulla",
  "Ulla Straus",
  "Perila",
  "Pontiac Streator",
  "Huerco S.",
  "Loidis",
  "Moin",
  "Four Tet",
  "Ben Bondy",
  "DJ Python",
  "Pendant",
  "mu tate",
  "LOG",
  "exael",
  "ultrafog",
  "Mount XLR",
  "Deadbeat",
  "Basic Channel",
  "Pole",
  "Flying Lotus",
  "Floating Points",
  "Alva Noto",
  "Rival Consoles",
  "Aphex Twin",
  "Bon Iver",
  "Joanne Robertson",
  "Aloisius",
  "Bianca Scout",
  "2k88",
  "Mount Kimbie",
  "Substance",
  "Vainqueur",
  "OK EG",
  "Upsammy",
  "Space Afrika",
  "Shinichi Atobe",
  "Susumu Yokota",
  "Demdike Stare",
  "Conna Haraway",
  "Deepchord",
  "U.e.",
  "Boards of Canada",
  "Felicia Atkinson",

  // Adjacency wave
  "Fields of Mist",
  "Sampha",
  "shinetiac",
  "Yussef Dayes",
  "Eyedress",
  "Iglooghost",
  "Amnesia Scanner",
  "Durutti Column",
  "Lorenzo Senni",
  "DJ Shadow",
  "Jacques Greene",
  "Nosaj Thing",
  "Jpegmafia",
  "Vegyn",
  "Max Cooper",
  "Noon",
  "LSDXOXO",
  "Sammy Virji",
  "Kwabs",
  "Carrier",
  "Meitei",
  "Zebra Katz",
  "Rustie",

  // Forward-thinking additions
  "Arooj Aftab",
  "Autechre",
  "Simo Cell",
  "Actress",
  "Aleksandra Słyż",
  "Antonina Nowacka",
  "John Talabot",
  "James Blake",
  "Piernikowski",
  "Lowra",
  "Smerz",
  "Loraine James",
  "Whatever the Weather",
  "Lucrecia Dalt",
  "Mica Levi",
  "Caterina Barbieri",
  "Kali Malone",
  "Bendik Giske",
  "emptyset",
  "k-lone",
  "Heith",
  "Malibu",
  "Martyn",
  "Squarepusher",

  // Crossover / pop-adjacent but ambitious production. Broader reach,
  // still in keeping with the forward-thinking remit.
  "Rosalía",
  "Overmono",
  "The Chemical Brothers",
  "Massive Attack",
  "Tricky",
  "Danny Brown",

  // Expansion wave - deep techno / dub / ambient lineage, classic IDM, left-
  // field hip-hop, Polish jazz + experimental, and newer curatorial names
  // surfacing in 2024-2025 DJ pools. Intentionally broad so sync coverage
  // catches the releases that define the genres around the site's core.
  "Leon Vynehall",
  "Verraco",
  "Kode9",
  "Burial",
  "Fluxion",
  "Amelie Lens",
  "Vladislav Delay",
  "Jan Jelinek",
  "Moritz von Oswald",
  "Mark Ernestus",
  "Maurizio",
  "Monolake",
  "Yagya",
  "William Basinski",
  "Kendrick Lamar",
  "Moor Mother",
  "billy woods",
  "Madlib",
  "MF DOOM",
  // KOSMOS - Polish jazz; disambiguate manually if Discogs finds multiple.
  "KOSMOS",
  "Ziomcy",
  "Karuzelkaaa",
  "Krenz",
  "Jamie xx",
  "Kaitlyn Aurelia Smith",
  "Special Guest DJ",
  "Caveman LSD",
  "Thom Yorke",
  "Throwing Snow",
  "Plaid",
  "The Field",
  "Ross from Friends",
  "DJ Boring",
  "Lone",
  "DJ Koze",
  "Ólafur Arnalds",
  "Jon Hopkins",
  "Clark",
  "Lee Gamble",
  "Boxcutter",
  "Ital Tek",
  "µ-Ziq",
  "Amon Tobin",
  "Arca",
  "Björk",
  "Apparat",
  "Ben Frost",
  "Biosphere",
  "Daisuke Tanabe",
  "Drexciya",
  "Nexciya",
  "FaltyDL",
  "Forest Swords",
  "GAS",
  "Synkro",
  "Visible Cloaks",
  "Nikita, the Wicked",
  "Jlin",
  "Koreless",
  "Mark Pritchard",
  "Photek",
  "Shigeto",
  "Tim Hecker",
  "Blawan",
  "Kangding Ray",
  "Fever Ray",
  "Olof Dreijer",
  "The Knife",
  "Sofie Birch",
  "Danny L Harle",
  "Div 4",
  "Sunn O)))",
  "Crystallmess",
  "Evian Christ",
  "Masayoshi Fujita",
  "Laurel Halo",
  "Pessimist",
  "Alessandro Cortini",
  "gyrofield",
  "Mister Water Wet",
  "Terekke",
  "Galcher Lustwerk",
  "Anthony Naples",
  "990x",
  "Palms Trax",
  "Zenker Brothers",
  "Hieroglyphic Being",
  "Nourished by Time",
  "MpeG",
  "The Pheromoans",
  "Coil",
  "Stara Rzeka",
  "Darkside",
  "Weval",
  "Romare",
  "Christian Löffler",
  "Nils Frahm",
  "DJ Seinfeld",
  "james K",
  "Om Unit",
  "Seefeel",
  "CS + Kreme",
  "Cleyra",
  "XENIA REAPER",
  "Sary Moussa",
  "Atrice",
  "upau",
  "Priori",
  "Notte Infinita",
  "Cousin",
  "key_asc",
  "nueen",
  "Eden Aurelius",
  "DJ Birdbath",
  "Pharoah Sanders",
  "DJ Plead",
  "Lyra Pramuk",

  // Added 2026-04 - curator-requested expansion.
  "aya",
  "96 Back",
  "Oli XL",
  "Clock DVA",
  "ex_libris",
  "Richie Culver",
  "Esdeekid",
  "Jim Legxacy",
  "Xexa",
  "xtclvr",
  "Klein",
  "Hype Williams",
  "ML Buch",
  "Blood Orange",
  "Oklou",
  "Croatian Amor",
  "Dijon",
  "Matthew Herbert",
  "Cinna Peyghamy",
  "Ricardo Villalobos",
  "fakemink",
  "Tiga",
  // "Susumu Yokota" and "Laurel Halo" already present above; kept single entry.
  "Rainy Miller",
];

/**
 * Labels to track via Discogs label search. The canonical form below is what
 * Discogs actually catalogues under - not always identical to the label's
 * own typography (e.g. Discogs has "Ilian Tape" not "ILIAN TAPE").
 *
 * When Discogs has multiple same-named labels, we disambiguate with `(N)`
 * suffix per Discogs convention.
 */
export const LABELS = [
  "Ilian Tape",
  "Houndstooth",
  "Knekelhuis",
  "YOUNG", // y-o-u-n-g.com
  "Fixed Abode",
  "SUPERNATURE",
  "Hyperdub",
  "Warp Records",
  "Brainfeeder",
  "Leaving Records",
  "Dais Records",
  "Sferic",
  "INDEX:Records",
  "Appendix.Files",
  "3XL",
  "Motion Ward",
  "AMF Records",
  "Cirrus",
  "Chain Reaction",
  "A Strange Child",
  "Twin System",
  "Ono Records",
  "Peak Oil",
  "Helix Records",
  "NAFF",
  "AD 93",
  "Modern Love",
  "Other People",
  "Latency",
  "Muscut",
  "Telrae",
  "WORLD MUSIC",
  "Tan Cressida",
  "Smalltown Supersound",
  "Mood Hut",
  "Isla",
  "Youth",
  "Good Morning Tapes",
  "R&S Records",
  "Ninja Tune",
  "Incienso",
  "Hivern Discs",
  "Parallaxe Editions",
  "Balmat",
  "Shelter Press",
  "Short Span",
  "FELT",
  "29 Speedway",
  "Mappa",
  "Posh Isolation",
  "West Mineral Ltd.",
  "PAN",
  "Ghostly International",
  "Opal Tapes",
  "100% Silk",
  "Lapsus",
  "Daisart",
  "12th Isle",
  "Theory Therapy",
  "Numbers",
  "Coastline Northern Cuts",
  "Mondoj",
  "Instant Classic",
  "5GATE TEMPLE",
  ".jpeg Artefacts",
  "unseelie",
  "co:clear",
  "Erased Tapes",
  "Raster-Noton",
  "Jagjaguwar",
  "Purely Physical",
  "Life Is Beautiful",
  "Geographic North",
  "Nyege Nyege Tapes",
  "Orange Milk Records",
  "OST", // ost.music.life - small experimental imprint
  "00effort",
  "YUKU",
];

/**
 * Festival lineup pages - scraped periodically to surface artists we don't
 * already track. Keep each entry limited to the CURRENT edition's lineup
 * page. Anything found gets written to `data/festival-suggestions.json` and
 * surfaced in admin, never auto-added to the pool.
 */
export const FESTIVALS = [
  {
    name: "Unsound",
    location: "Kraków, Poland",
    url: "https://www.unsound.pl/en/festival/unsound-kra-w",
  },
  {
    name: "Berlin Atonal",
    location: "Berlin, Germany",
    url: "https://berlin-atonal.com/",
  },
  {
    name: "Rewire",
    location: "The Hague, Netherlands",
    url: "https://www.rewirefestival.nl/programme",
  },
];

/**
 * News / radio sources monitored for artist discovery. Only NTS is
 * automatable today (RA has no release feed, Boomkat has no public API).
 * The Quietus publishes a public RSS feed covering reviews, news, and
 * "singles of the week" - parseable with any feed reader.
 */
export const NEWS_SOURCES = [
  {
    name: "NTS Radio",
    // NTS's live shows feed - used by sync-nts.mjs to extract host names.
    url: "https://www.nts.live/api/v2/shows",
    notes: "Scrape show hosts; cross-reference with ARTISTS; suggest unknowns.",
  },
  {
    name: "The Quietus",
    // Site-wide RSS. Covers reviews + news; the release and Bakers Dozen
    // columns are the richest source of artists we might not already track.
    // Also useful: https://thequietus.com/reviews (scrape for review bylines
    // and artist names) when the RSS isn't enough.
    url: "https://thequietus.com/feed",
    notes:
      "Parse titles/descriptions; extract artist names; suggest unknowns via the festival-suggestions-style review queue.",
  },
];
